"""
MacroFilterSummaryService.

Directly maps the AI-generated JSON from MacroSearchBatch into MacroSummary.
Bypasses any secondary LLM summarization step.
"""
from __future__ import annotations

import logging
import uuid
import datetime
from sqlalchemy.orm import Session

from models.discovery import MacroSearchBatch, MacroSummary

logger = logging.getLogger(__name__)

SUMMARY_TYPE = "MACRO_FILTER"

CATEGORIES = [
    "INTEREST_RATES_AND_LIQUIDITY",
    "COMMODITY_AND_INPUT_COSTS",
    "GOVERNMENT_POLICY_AND_SPENDING",
    "DEMAND_CONDITIONS",
]
VALID_CONDITIONS = {"IMPROVING", "DETERIORATING", "STABLE", "MIXED", "UNCERTAIN"}
VALID_DIRECTIONS = {"POSITIVE", "NEGATIVE", "NEUTRAL", "MIXED", "UNCERTAIN"}

W_BATCH_UNAVAILABLE = "MACRO_SEARCH_BATCH_UNAVAILABLE"
W_BATCH_EMPTY = "MACRO_BATCH_RESULTS_EMPTY"

class MacroFilterSummaryService:
    """
    Reads the Parallel generated JSON from MacroSearchBatch and 
    formats it into a MacroSummary record.
    """

    def __init__(self, discovery_session: Session):
        self._disc = discovery_session

    def generate_macro_filter_summary(self, run_id: str) -> dict:
        """
        Extract the structured JSON from the latest batch and build MacroSummary.
        """
        existing = (
            self._disc.query(MacroSummary)
            .filter_by(run_id=run_id, summary_type=SUMMARY_TYPE)
            .first()
        )
        if existing and existing.status in ("COMPLETED", "COMPLETED_WITH_WARNINGS"):
            return {"status": existing.status, "metadata": {"result_id": existing.id}}

        batch_id = f"macro-parallel-{run_id}"
        batch = (
            self._disc.query(MacroSearchBatch)
            .filter_by(run_id=run_id, id=batch_id)
            .first()
        )

        if not existing:
            existing = MacroSummary(
                id=str(uuid.uuid4()),
                run_id=run_id,
                source_batch_id=batch_id,
                summary_type=SUMMARY_TYPE,
                status="PENDING",
                category_summaries={},
                overall_synthesis={},
                document_statistics={},
                warnings=[]
            )
            self._disc.add(existing)
            self._disc.flush()

        if not batch or batch.status not in ("COMPLETED", "COMPLETED_WITH_WARNINGS"):
            existing.status = "FAILED"
            existing.warnings = [W_BATCH_UNAVAILABLE]
            self._disc.commit()
            return {"status": "FAILED", "warnings": existing.warnings, "metadata": {"result_id": existing.id}}

        if not batch.results or not isinstance(batch.results, list) or len(batch.results) == 0:
            existing.status = "FAILED"
            existing.warnings = [W_BATCH_EMPTY]
            self._disc.commit()
            return {"status": "FAILED", "warnings": existing.warnings, "metadata": {"result_id": existing.id}}

        # Extract the JSON generated by Parallel
        parsed_json = batch.results[0]
        
        # Map to category_summaries matching the expected downstream keys
        category_summaries = {
            "INTEREST_RATES_AND_LIQUIDITY": {
                "category": "INTEREST_RATES_AND_LIQUIDITY",
                "condition": "MIXED",
                "summary": parsed_json.get("interest_rates", ""),
                "key_developments": [],
                "contradictions": [],
                "missing_information": [],
                "used_source_ids": [],
                "ignored_source_ids": []
            },
            "COMMODITY_AND_INPUT_COSTS": {
                "category": "COMMODITY_AND_INPUT_COSTS",
                "condition": "MIXED",
                "summary": parsed_json.get("commodity_input_costs", ""),
                "key_developments": [],
                "contradictions": [],
                "missing_information": [],
                "used_source_ids": [],
                "ignored_source_ids": []
            },
            "GOVERNMENT_POLICY_AND_SPENDING": {
                "category": "GOVERNMENT_POLICY_AND_SPENDING",
                "condition": "MIXED",
                "summary": parsed_json.get("government_policies", ""),
                "key_developments": [],
                "contradictions": [],
                "missing_information": [],
                "used_source_ids": [],
                "ignored_source_ids": []
            },
            "DEMAND_CONDITIONS": {
                "category": "DEMAND_CONDITIONS",
                "condition": "MIXED",
                "summary": parsed_json.get("demand_conditions", ""),
                "key_developments": [],
                "contradictions": [],
                "missing_information": [],
                "used_source_ids": [],
                "ignored_source_ids": []
            }
        }
        
        overall_synthesis = {
            "overall_summary": "Aggregated Macro View",
            "dominant_condition": "MIXED",
            "dominant_themes": [],
            "cross_category_conflicts": [],
            "category_conditions": {},
            "missing_categories": []
        }

        existing.category_summaries = category_summaries
        existing.overall_synthesis = overall_synthesis
        existing.status = "COMPLETED"
        existing.updated_at = datetime.datetime.utcnow()
        self._disc.commit()

        return {"status": "COMPLETED", "metadata": {"result_id": existing.id}}
