"""Add technical metric fields and unique constraints

Revision ID: 7420b4aa7335
Revises: b29be803889e
Create Date: 2026-07-13 12:10:38.548734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7420b4aa7335'
down_revision: Union[str, Sequence[str], None] = 'b29be803889e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_technical_metrics', sa.Column('as_of_date', sa.Date(), nullable=True))
    op.add_column('company_technical_metrics', sa.Column('company_candle_date', sa.String(), nullable=True))
    op.add_column('company_technical_metrics', sa.Column('benchmark_candle_date', sa.String(), nullable=True))
    op.add_column('company_technical_metrics', sa.Column('current_close', sa.Float(), nullable=True))
    op.add_column('company_technical_metrics', sa.Column('start_close', sa.Float(), nullable=True))
    op.add_column('company_technical_metrics', sa.Column('benchmark_current_close', sa.Float(), nullable=True))
    op.add_column('company_technical_metrics', sa.Column('benchmark_start_close', sa.Float(), nullable=True))
    op.add_column('company_technical_metrics', sa.Column('company_consistency_score', sa.Float(), nullable=True))
    op.add_column('company_technical_metrics', sa.Column('return_available', sa.Boolean(), nullable=True))
    op.add_column('company_technical_metrics', sa.Column('volume_available', sa.Boolean(), nullable=True))
    op.add_column('company_technical_metrics', sa.Column('consistency_available', sa.Boolean(), nullable=True))
    op.add_column('company_technical_metrics', sa.Column('warnings', sa.JSON(), nullable=True))
    op.create_unique_constraint('uq_technical_run_company_horizon', 'company_technical_metrics', ['run_id', 'source_company_id', 'horizon'])
    op.create_unique_constraint('uq_group_score_run_type_name_horizon', 'group_scores', ['run_id', 'entity_type', 'entity_name', 'horizon'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_group_score_run_type_name_horizon', 'group_scores', type_='unique')
    op.drop_constraint('uq_technical_run_company_horizon', 'company_technical_metrics', type_='unique')
    op.drop_column('company_technical_metrics', 'warnings')
    op.drop_column('company_technical_metrics', 'consistency_available')
    op.drop_column('company_technical_metrics', 'volume_available')
    op.drop_column('company_technical_metrics', 'return_available')
    op.drop_column('company_technical_metrics', 'company_consistency_score')
    op.drop_column('company_technical_metrics', 'benchmark_start_close')
    op.drop_column('company_technical_metrics', 'benchmark_current_close')
    op.drop_column('company_technical_metrics', 'start_close')
    op.drop_column('company_technical_metrics', 'current_close')
    op.drop_column('company_technical_metrics', 'benchmark_candle_date')
    op.drop_column('company_technical_metrics', 'company_candle_date')
    op.drop_column('company_technical_metrics', 'as_of_date')
    # ### end Alembic commands ###
