"""Add final fundamental status and eligibility

Revision ID: a3cee42bf7ec
Revises: c0a43d62752d
Create Date: 2026-07-13 15:35:05.415954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3cee42bf7ec'
down_revision: Union[str, Sequence[str], None] = 'c0a43d62752d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_fundamental_metrics', sa.Column('fundamental_status', sa.String(), nullable=True))
    op.add_column('company_fundamental_metrics', sa.Column('fundamental_eligible_for_selection', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_fundamental_metrics', 'fundamental_eligible_for_selection')
    op.drop_column('company_fundamental_metrics', 'fundamental_status')
    # ### end Alembic commands ###
