"""Fix group_scores hierarchy unique constraint

Revision ID: c0a43d62752d
Revises: 7420b4aa7335
Create Date: 2026-07-13 12:16:13.682222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a43d62752d'
down_revision: Union[str, Sequence[str], None] = '7420b4aa7335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill any existing NULLs to empty string before enforcing NOT NULL.
    op.execute("UPDATE group_scores SET parent_sector = '' WHERE parent_sector IS NULL")
    op.execute("UPDATE group_scores SET parent_industry = '' WHERE parent_industry IS NULL")

    op.alter_column('group_scores', 'parent_sector',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default='')
    op.alter_column('group_scores', 'parent_industry',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default='')
    op.drop_constraint(op.f('uq_group_score_run_type_name_horizon'), 'group_scores', type_='unique')
    op.create_unique_constraint('uq_group_score_hierarchy_horizon', 'group_scores', ['run_id', 'entity_type', 'entity_name', 'parent_sector', 'parent_industry', 'horizon'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_group_score_hierarchy_horizon', 'group_scores', type_='unique')
    op.create_unique_constraint(op.f('uq_group_score_run_type_name_horizon'), 'group_scores', ['run_id', 'entity_type', 'entity_name', 'horizon'], postgresql_nulls_not_distinct=False)
    op.alter_column('group_scores', 'parent_industry',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('group_scores', 'parent_sector',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
