"""Initial discovery tables

Revision ID: ece614eb4274
Revises: 
Create Date: 2026-07-13 11:35:58.101535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece614eb4274'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_fundamental_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('source_company_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('basic_industry', sa.String(), nullable=True),
    sa.Column('growth_score', sa.Float(), nullable=True),
    sa.Column('profitability_score', sa.Float(), nullable=True),
    sa.Column('financial_strength_score', sa.Float(), nullable=True),
    sa.Column('earnings_quality_score', sa.Float(), nullable=True),
    sa.Column('final_fundamental_score', sa.Float(), nullable=True),
    sa.Column('benchmark_level_used', sa.String(), nullable=True),
    sa.Column('data_coverage', sa.Float(), nullable=True),
    sa.Column('unavailable_fields', sa.JSON(), nullable=True),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_technical_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('source_company_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('basic_industry', sa.String(), nullable=True),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('company_return', sa.Float(), nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('relative_return', sa.Float(), nullable=True),
    sa.Column('average_volume_current', sa.Float(), nullable=True),
    sa.Column('average_volume_previous', sa.Float(), nullable=True),
    sa.Column('volume_change', sa.Float(), nullable=True),
    sa.Column('positive_period_ratio', sa.Float(), nullable=True),
    sa.Column('benchmark_outperformance_ratio', sa.Float(), nullable=True),
    sa.Column('data_coverage', sa.Float(), nullable=True),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovery_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_date', sa.String(), nullable=True),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source_data_as_of', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovery_selections',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_name', sa.String(), nullable=True),
    sa.Column('parent_sector', sa.String(), nullable=True),
    sa.Column('parent_industry', sa.String(), nullable=True),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('constituent_count', sa.Integer(), nullable=True),
    sa.Column('eligible_constituent_count', sa.Integer(), nullable=True),
    sa.Column('technical_return_score', sa.Float(), nullable=True),
    sa.Column('technical_breadth_score', sa.Float(), nullable=True),
    sa.Column('technical_volume_score', sa.Float(), nullable=True),
    sa.Column('technical_consistency_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('fundamental_growth_score', sa.Float(), nullable=True),
    sa.Column('fundamental_profitability_score', sa.Float(), nullable=True),
    sa.Column('fundamental_financial_strength_score', sa.Float(), nullable=True),
    sa.Column('fundamental_earnings_quality_score', sa.Float(), nullable=True),
    sa.Column('fundamental_score', sa.Float(), nullable=True),
    sa.Column('macro_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('data_coverage', sa.Float(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('macro_entity_impacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('macro_search_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('macro_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_summaries')
    op.drop_table('macro_search_batches')
    op.drop_table('macro_entity_impacts')
    op.drop_table('group_scores')
    op.drop_table('discovery_selections')
    op.drop_table('discovery_runs')
    op.drop_table('company_technical_metrics')
    op.drop_table('company_fundamental_metrics')
    # ### end Alembic commands ###
